### ISSUE TITLE
under serving function has register err

### ISSUE THREAD

**Issue by fengpengyun** [OpenFunction/functions-framework-go#14]
> ## under serving function has register err
> 2021/09/18 01:48:43 Failed to register: Function failed to register: unrecognized function
> 
> So I checked functions code of of_functions_framework / template.go.
> 
> ```go
> func register(fn interface{}) error {
> 	ctx := context.Background()
> 	if fnHTTP, ok := fn.(func(http.ResponseWriter, *http.Request)); ok {
> 		if err := functionframeworks.RegisterHTTPFunction(ctx, fnHTTP); err != nil {
> 			return fmt.Errorf("Function failed to register: %v\n", err)
> 		}
> 	} else if fnCloudEvent, ok := fn.(func(context.Context, cloudevents.Event) error); ok {
> 		if err := functionframeworks.RegisterCloudEventFunction(ctx, fnCloudEvent); err != nil {
> 			return fmt.Errorf("Function failed to register: %v\n", err)
> 		}
> 	} else if fnOpenFunction, ok := fn.(func(*ofctx.OpenFunctionContext, []byte) int); ok {
> 		if err := functionframeworks.RegisterOpenFunction(ctx, fnOpenFunction); err != nil {
> 			return fmt.Errorf("Function failed to register: %v\n", err)
> 		}
> 	} else {
> 		err := errors.New("unrecognized function")
> 		return fmt.Errorf("Function failed to register: %v\n", err)
> 	}
> 	return nil
> }
> ```
> 
> It will output err after else, that is, it does not recognize
> 
> ```go
> fn.(func(*ofctx.OpenFunctionContext, []byte) int)
> ```
> 
> @tpiperatgod

**Comment by tpiperatgod** [comment]
Hi, I built the go builder images from the latest branch of the builder repo, which are:

**openfunctiondev/go115-builder:v0.2.2**
**openfunctiondev/go116-builder:v0.2.2**

You can try running `docker pull` locally to update the images and then create the function again

**Comment by fengpengyun** [comment]
This is the result of serving after pulling the v0.2.2 image. I think it is still the problem of the builder.

**Comment by benjaminhuo** [comment]
> This is the result of serving after pulling the v0.2.2 image. I think it is still the problem of the builder.

you can docker rmi all the old v0.2.2 image and try again

**Comment by benjaminhuo** [comment]
the v0.2.2 image has been updated

**Comment by fengpengyun** [comment]
After deleting the image, I pull again and then create function, but there are new problems。
under build step create,：
```text
 ===> DETECTING

3 of 5 buildpacks participating

openfunction.go.of-functions-framework 0.0.1

google.go.build 0.9.0

google.utils.label 0.0.1

===> ANALYZING

Restoring metadata for "openfunction.go.of-functions-framework:functions-framework" from app image

Restoring metadata for "google.go.build:bin" from app image

===> RESTORING

===> BUILDING

openfunction.go.of-functions-framework

=== Go - OpenFunction Functions Framework (openfunction.go.of-functions-framework@0.0.1) ===

--------------------------------------------------------------------------------

Running "go run /cnb/buildpacks/openfunction.go.of-functions-framework/0.0.1/converter/get_package/main.go -dir /workspace/source/functions/OpenFuncAsync/logs-handler-function/serverless_function_source_code (GOCACHE=/tmp/serverless_function_app192659750)"

logs_handler_functionDone "go run /cnb/buildpacks/openfunction.go.of-functions-framewor..." (476.100955ms)

go.sum not found, generating using "go mod tidy"

Failure: (ID: 32633c29) go: github.com/prometheus/alertmanager@v0.22.2 requires

github.com/go-openapi/swag@v0.19.15/go.mod: verifying module: github.com/go-openapi/swag@v0.19.15/go.mod: checking tree#6977842 against tree#6978050: reading https://goproxy.cn/sumdb/sum.golang.org/tile/8/0/x027/257: 404 Not Found

server response: not found: not found

ERROR: failed to build: exit status 1
```

**Comment by tpiperatgod** [comment]
Can you try "https://goproxy.io"?

**Comment by fengpengyun** [comment]
I don't know the reason for the above error，but i set env "https://goproxy.io".
so,
After deleting the image again, I pull again and then create function, but this is a same problem。
under function log
```text
2021/09/18 03:27:50 Failed to register: Function failed to register: unrecognized function
```
under daprd log
```text

{"app_id":"logs-handler-serving-7bphh-default","instance":"logs-handler-serving-7bphh-v100-m6mdn-5569484cf4-rwhf5","level":"info","msg":"application protocol: grpc. waiting on port 8080. This will block until the app is listening on that port.","scope":"dapr.runtime","time":"2021-09-18T03:28:29.401546037Z","type":"log","ver":"1.3.1"}

{"app_id":"logs-handler-serving-7bphh-default","instance":"logs-handler-serving-7bphh-v100-m6mdn-5569484cf4-rwhf5","level":"info","msg":"starting workload cert expiry watcher. current cert expires on: 2021-09-19 03:43:29 +0000 UTC","scope":"dapr.runtime.grpc.internal","time":"2021-09-18T03:28:29.401790824Z","type":"log","ver":"1.3.1"}

{"app_id":"logs-handler-serving-7bphh-default","instance":"logs-handler-serving-7bphh-v100-m6mdn-5569484cf4-rwhf5","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2021-09-18T03:28:33.23621045Z","type":"log","ver":"1.3.1"}

{"app_id":"logs-handler-serving-7bphh-default","instance":"logs-handler-serving-7bphh-v100-m6mdn-5569484cf4-rwhf5","level":"debug","msg":"{ERR_HEALTH_NOT_READY dapr is not ready}","scope":"dapr.runtime.http","time":"2021-09-18T03:28:36.782304654Z","type":"log","ver":"1.3.1"}
```

**Comment by tpiperatgod** [comment]
Can you provide the image id?

**Comment by fengpengyun** [comment]
The image id is 166582cbaf54.

**Comment by tpiperatgod** [comment]
This is the latest version. Do you have multiple nodes? You may need to make sure that the images on each node are upgraded to that version.

**Comment by tpiperatgod** [comment]
Would you like to join the discussion in our community: https://kubesphere.slack.com/?redir=%2Farchives%2FC021XAR3CG3

**Comment by fengpengyun** [comment]
I specified nodeName, so there will be no scheduling to other nodes。

I've been following kubesphere for a long time. I really want to participate in the ecological construction of kubesphere. I'm also honored to can join the discussion in your community。

**Comment by tpiperatgod** [comment]
> I see from KS that it is in the node of the latest image。
> 
> I've been following kubesphere for a long time. I really want to participate in the ecological construction of kubesphere. I'm also honored to can join the discussion in your community。

Great, perhaps we can discuss this more efficiently in slack
