### ISSUE TITLE
[Proposal]Using uniform function signatures

### ISSUE THREAD

**Issue by tpiperatgod** [OpenFunction/functions-framework-go#16]
# Motivation

Currently, **functions-framework-go** needs to handle three different functions:

- http function `func(http.ResponseWriter, *http.Request)`
- cloudevent function `func(context.Context, cloudevents.Event) error`
- openfunction functions-framework spec based function `func(*ofctx.OpenFunctionContext, []byte) ofctx.RetValue`

This is not user-friendly and is not conducive to maintenance and evolution.

# Main goal
Use functions(unified function signatures) based on the openfunction functions-framework specification to support different functions.

**Comment by benjaminhuo** [comment]
Agree

**Comment by benjaminhuo** [comment]
Close via https://github.com/OpenFunction/functions-framework-go/pull/22
