### ISSUE TITLE
Update Http Backend as mux is archived

### ISSUE THREAD

**Issue by lizzzcai** [OpenFunction/functions-framework-go#68]
The [gorilla/mux](https://github.com/gorilla/mux) is in public archive mode due to [lack of maintainers](https://github.com/gorilla/mux/issues/659#issuecomment-1344468929). We should switch to other implementations like [fasthttp](https://github.com/valyala/fasthttp)(used by Dapr) or other alternatives. If you have any good alternatives, please share them in the comment. Thanks.

**Comment by benjaminhuo** [comment]
@lizzzcai would you help to switch to fasthttp?

**Comment by lizzzcai** [comment]
> @lizzzcai would you help with switching to fasthttp?

Hi @benjaminhuo , sure, I can help with it, will do it in January.

**Comment by lizzzcai** [comment]
> @lizzzcai would you help with switching to fasthttp?

Hi @benjaminhuo , I quickly checked fasthttp yesterday, it probably does not fit here as it doesn't support request routing (path variables is not supported) and it is `incompatible` with net/http (need a [converter](https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp)), can find details [here](https://github.com/valyala/fasthttp#faq).

My idea is to find an alternative router which is compatible with `net/http` so that it will be easier to maintain and switch to another if the similar issue happens again. ([dapr](https://github.com/dapr/dapr/issues/4979) is switching from fasthttp to net/http).

One alternative I found is [go-chi/chi](https://github.com/go-chi/chi/), but I have to test if all the features we used in `mux` are implemented in `chi`, and the worse case is there will be some breaking changes, what do you think?

**Comment by benjaminhuo** [comment]
> > @lizzzcai would you help with switching to fasthttp?
> 
> Hi @benjaminhuo , I quickly checked fasthttp yesterday, it probably does not fit here as it doesn't support request routing (path variables is not supported) and it is `incompatible` with net/http (need a [converter](https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp)), can find details [here](https://github.com/valyala/fasthttp#faq).
> 
> My idea is to find an alternative router which is compatible with `net/http` so that it will be easier to maintain and switch to another if the similar issue happens again. ([dapr](https://github.com/dapr/dapr/issues/4979) is switching from fasthttp to net/http).
> 
> One alternative I found is [go-chi/chi](https://github.com/go-chi/chi/), but I have to test if all the features we used in `mux` are implemented in `chi`, and the worse case is there will be some breaking changes, what do you think?

@wanjunlei Are we using https://github.com/emicklei/go-restful in KubeSphere?

**Comment by benjaminhuo** [comment]
> One alternative I found is [go-chi/chi](https://github.com/go-chi/chi/), but I have to test if all the features we used in `mux` are implemented in `chi`, and the worse case is there will be some breaking changes, what do you think?

chi looks good, we can give it a try.
It's indeed an alternative to gorilla/mux. The feature you want to use cannot be fulfilled by net/http right?
https://markphelps.me/posts/4-things-to-consider-when-choosing-a-go-api-framework/

**Comment by wanjunlei** [comment]
> > > @lizzzcai would you help with switching to fasthttp?
> > 
> > 
> > Hi @benjaminhuo , I quickly checked fasthttp yesterday, it probably does not fit here as it doesn't support request routing (path variables is not supported) and it is `incompatible` with net/http (need a [converter](https://github.com/valyala/fasthttp#switching-from-nethttp-to-fasthttp)), can find details [here](https://github.com/valyala/fasthttp#faq).
> > My idea is to find an alternative router which is compatible with `net/http` so that it will be easier to maintain and switch to another if the similar issue happens again. ([dapr](https://github.com/dapr/dapr/issues/4979) is switching from fasthttp to net/http).
> > One alternative I found is [go-chi/chi](https://github.com/go-chi/chi/), but I have to test if all the features we used in `mux` are implemented in `chi`, and the worse case is there will be some breaking changes, what do you think?
> 
> @wanjunlei Are we using https://github.com/emicklei/go-restful in KubeSphere?

Yes

**Comment by lizzzcai** [comment]
> chi looks good, we can give it a try. https://markphelps.me/posts/4-things-to-consider-when-choosing-a-go-api-framework/ It's indeed an alternative to gorilla/mux. The feature you want to use cannot be fulfilled by net/http right?

example like`"/hello/{name}"` is not supported in `net/http`. `chi` looks lightweight and is actively maintained, I can give it a try first.
