### ISSUE TITLE
RuntimeContext is shared accross request by pointer , SetSyncRequest and GetSyncRequest  is unpredictable ?

### ISSUE THREAD

**Issue by binnn6** [OpenFunction/functions-framework-go#75]
```go
func (r *Runtime) RegisterHTTPFunction(
	ctx ofctx.RuntimeContext,
	prePlugins []plugin.Plugin,
	postPlugins []plugin.Plugin,
	rf *functions.RegisteredFunction,
) error {
	route := r.handler.HandleFunc(rf.GetPath(), func(w http.ResponseWriter, r *http.Request) {
		rm := runtime.NewRuntimeManager(ctx, prePlugins, postPlugins)
		// save the Vars into the context
		_ctx := ofctx.CtxWithVars(r.Context(), ofctx.Vars(r))
		rm.FuncContext.SetNativeContext(_ctx)
		rm.FuncContext.SetSyncRequest(w, r.WithContext(_ctx))
		defer RecoverPanicHTTP(w, "Function panic")
		rm.FunctionRunWrapperWithHooks(rf.GetHTTPFunction())
	})

	// add methods matcher if any
	methods := rf.GetFunctionMethods()
	if len(methods) > 0 {
		route.Methods(methods...)
	}

	return nil
}
```
Since RuntimeContext is shared accross request by pointer , SetSyncRequest and GetSyncRequest  is unpredictable ? or it should pass by value?

**Comment by binnn6** [comment]
pr here https://github.com/OpenFunction/functions-framework-go/pull/76/commits/7b616e92fcaf9c1c86c987cf4f292805554eb823

**Comment by wanjunlei** [comment]
Why SetSyncRequest and GetSyncRequest is unpredictable? Is there anyone who will change the RuntimeContext?

**Comment by binnn6** [comment]
Every request will call SetSyncRequest, so change RuntimeContext. So while just after request A call SetSyncRequest, request B call GetSyncRequest, request B will not be processed. since request B get request and response set by Request A.

**Comment by binnn6** [comment]
Reqeust A and Request B come in at the same time， Reqeust A  may be exec 2 times, while Reqeust B 0 times. @wanjunlei

**Comment by wanjunlei** [comment]
OK, I understand.
